### ISSUE TITLE
error: At least one OAuth2/OpenID Connect flow must be enabled.

### ISSUE THREAD

**Issue by fopsdev** [capesean/openiddict-test#20]
got this error with newest bits (visual studio update 3 including a kb patch from today) on a fresh git clone:

```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=At least one OAuth2/OpenID Connect flow must be enabled.
  Source=OpenIddict.Core
  StackTrace:
       at Microsoft.AspNetCore.Builder.OpenIddictExtensions.UseOpenIddict(IApplicationBuilder app)
       at openiddicttest.Startup.Configure(IApplicationBuilder app, IDatabaseInitializer databaseInitializer)


```

**Comment by kevinchalet** [comment]
With the latest OpenIddict bits, all the endpoints are disabled by default and flows must be enabled manually.

Calling `EnableTokenEndpoint()` and `AllowPasswordFlow()` should be enough:

``` csharp
services.AddOpenIddict<ApplicationUser, ApplicationRole, ApplicationDbContext>()
    .DisableHttpsRequirement()
    .EnableTokenEndpoint("/connect/token")
    .AllowPasswordFlow()
    .UseJsonWebTokens();
```

**Comment by fopsdev** [comment]
yeah that was it :) thanks
will make a PR if possible

**Comment by kevinchalet** [comment]
In the meantime, maybe you should leave this ticket open to make it more visible?

**Comment by fopsdev** [comment]
ok, good idea

**Comment by DavidDury** [comment]
You have also to AllowRefreshTokenFlow(), otherwise you will get : "The 'offline_access' scope is not allowed."

```
 services.AddOpenIddict<ApplicationUser, ApplicationRole, ApplicationDbContext>()
            .DisableHttpsRequirement()
            .EnableTokenEndpoint("/connect/token")
            .AllowPasswordFlow()
            .AllowRefreshTokenFlow()
            .UseJsonWebTokens();
```

**Comment by fopsdev** [comment]
I've just added it to the PR, thanks
